### PR TITLE
Moved everything from OS2forms Forløb to OS2forms EGIR repo.

### PR DESCRIPTION
**Pull request by agger-magenta**
In order to test, use the branch `45293_merge_code_from_old_repo` in the `os2forms_egir_profile` repository.

### CODE REVIEW

**Review by madsnorgaard — CHANGES_REQUESTED** [review]
Approved on condition we remove composer.lock as this is not standard to have in a module + fix translation directory issue as commented. Other issues will be addressed at a later stage during review.

**Comment by nina-j** [comment]
We need to set `request_timeout: '120'` in the employee feed settings. https://github.com/OS2Forms/os2forms_egir/pull/2/files#diff-f63a95ac66e8bfb0dc189f461959db395478809d47062c8640fbd5ec4fa30affR21

**Comment by nina-j** [comment]
Something is amiss when I try to access the task console. It looks like a maestro db error? 
image

This happens after I submit a webform (Request New External in this case).

**Comment by agger-magenta** [comment]
Indeed. I'm also having trouble building it with all dependencies, so it's not quite ready to go yet.

**Pull request merged**
